const express = require('express');
const controller = require('./video.controller');
const auth = require('../middleware/auth.middleware');
const role = require('../middleware/role.middleware');
const upload = require('../middleware/upload.middleware');
const router = express.Router();
router.get('/feed', controller.getVideoFeed);
router.get('/stats/list', auth, role('ADMIN','STAFF'), controller.getStats);
router.get('/', auth, role('ADMIN','STAFF'), controller.getVideos);
router.get('/:id', controller.getVideoById);
router.post('/', auth, upload.fields([{ name: 'thumbnail', maxCount: 1 }, { name: 'video', maxCount: 1 }]), controller.createVideo);
router.post('/:id/like', auth, controller.toggleLike);
router.post('/:id/save', auth, controller.toggleSave);
router.post('/:id/comment', auth, controller.addComment);
router.post('/:id/view', controller.addView);
router.put('/:id', auth, role('ADMIN','STAFF'), upload.fields([{ name: 'thumbnail', maxCount: 1 }, { name: 'video', maxCount: 1 }]), controller.updateVideo);
router.put('/:id/approve', auth, role('ADMIN','STAFF'), controller.approveVideo);
router.put('/:id/reject', auth, role('ADMIN','STAFF'), controller.rejectVideo);
router.delete('/:id', auth, role('ADMIN','STAFF'), controller.deleteVideo);
module.exports = router;
